#!/usr/bin/env python3.10

#Metric  BMI = (weight in kg / height in meters square(**2))
#Imperial BMI * 703

def gather_info():
    height = float(input("What is your height? (inches or meters) "))
    weight = float(input("What is your weight? (pounds or kilograms) "))
    system = input("Are your measurements in metric or imperial units? ").lower().strip()
    return (height, weight, system)

def cal_bmi(weight, height, system='metric'):
    """
Return BMI for the given weight, height, and meaurement system.
    """
    if system == 'metric':
        bmi = (weight/(height**2))
    else:
        bmi = 703*(weight/(height**2))
    return bmi

while True:
    height, weight, system = gather_info()
    if system.startswith('i'):
        bmi = cal_bmi(weight, system=system, height=height)
        print(f"Your BMI is: {bmi}")
        break
    elif system.startswith('m'):
        bmi = cal_bmi(weight, height)
        print(f"Your BMI is: {bmi}")
        break
    else:
        print("Error: Unknown measurement system. Please use imperial or metric.")
